fragment UserInfo on User {
  id
  username
}

fragment NoteInfo on Note {
  id
  title
  body
  createdAt
  updatedAt
}

query CurrentUser {
  currentUser {
    ...UserInfo
  }
}

query Notes {
  notes {
    ...NoteInfo
  }
}

query Note($id: String!) {
  note(id: $id) {
    ...NoteInfo
  }
}

mutation SignUp($email: String!, $username: String!, $password: String!) {
  signUp(email: $email, username: $username, password: $password) {
    ...UserInfo
  }
}

mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ...UserInfo
  }
}

mutation AddNote($title: String!, $body: String!) {
  addNote(title: $title, body: $body) {
    ...NoteInfo
  }
}

mutation UpdateNote($id: String!, $title: String!, $body: String!) {
  updateNote(id: $id, title: $title, body: $body) {
    ...NoteInfo
  }
}

mutation RemoveNore($id: String!) {
  removeNote(id: $id)
}
